class DecisionExecutor:
    """
    Executes decisions generated by reasoning layer.
    """

    def execute(
        self,
        reasoning
    ):

        risk = reasoning.get(
            "threat_assessment",
            "LOW"
        )


        if risk == "HIGH":

            action = {
                "action":
                    "incident_response",

                "priority":
                    "critical",

                "approval":
                    "required"
            }


        else:

            action = {
                "action":
                    "monitor",

                "priority":
                    "normal",

                "approval":
                    "not_required"
            }


        return action